### ISSUE TITLE
Perl crashes while using fatal warnings in callback

### ISSUE THREAD

**Issue by avkhozov** [miyagawa/Twiggy#44]
Example of application: https://gist.github.com/avkhozov/86c88d88fd4ac68f5342#file-test-psgi

It's crash on 5.20 (Segmentation fault) and crash on 5.14 (panic: POPSTACK)

**Comment by miyagawa** [comment]
when a pure perl program (your own code, as well as Twiggy) crashes, it's either a bug in Perl or a problem with the upstream XS code, in this case it's AnyEvent and its binding library. You might also like to check which AnyEvent backend you're using and try with other backends.

**Comment by miyagawa** [comment]
I'm not claiming that this isn't a bug in Twiggy per se, but at least a bug in Twiggy should not crash with a segmentation fault.

**Comment by avkhozov** [comment]
Well, thanks for answer!
