### ISSUE TITLE
Failing tests on RHEL6

### ISSUE THREAD

**Issue by toddbruner** [miyagawa/Twiggy#48]
Customer needs this on RHEL6 (I know...)

Log below.  Is it safe to ignore failed test and force install?  Thank you for your help...

cpanm Twiggy build log:

cpanm (App::cpanminus) 1.7034 on perl 5.010001 built for x86_64-linux-thread-multi
Work directory is /root/.cpanm/work/1433346584.13768
You have make /usr/bin/make
You have LWP 5.833
You have /bin/tar: tar (GNU tar) 1.23
Copyright (C) 2010 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by John Gilmore and Jay Fenlason.
You have /usr/bin/unzip
Searching Task::Plack () on cpanmetadb ...
--> Working on Task::Plack
Fetching http://www.cpan.org/authors/id/M/MI/MIYAGAWA/Task-Plack-0.28.tar.gz
-> OK
Unpacking Task-Plack-0.28.tar.gz
Entering Task-Plack-0.28
Checking configure dependencies from META.json
Checking if you have Module::Build::Tiny 0.019 ... Yes (0.039)
Configuring Task-Plack-0.28
Running Build.PL
Creating new 'Build' script for 'Task-Plack' version '0.28'
-> OK
Checking dependencies from MYMETA.json ...
Checking if you have Plack::Middleware::ConsoleLogger 0.04 ... Yes (0.05)
Checking if you have CGI::Emulate::PSGI 0.15 ... Yes (0.20)
Checking if you have CGI::Compile 0.16 ... Yes (0.19)
Checking if you have Plack::Middleware::Auth::Digest 0.04 ... Yes (0.05)
Checking if you have FCGI::ProcManager 0.24 ... Yes (0.25)
Checking if you have Starman 0.3011 ... Yes (0.4013)
Checking if you have CGI::PSGI 0.15 ... Yes (0.15)
Checking if you have Plack::Middleware::Deflater 0.08 ... Yes (0.12)
Checking if you have Plack::App::Proxy 0.27 ... Yes (0.29)
Checking if you have IO::Handle::Util 0.01 ... Yes (0.01)
Checking if you have FCGI::Client 0.08 ... Yes (0.08)
Checking if you have FCGI 0.74 ... Yes (0.77)
Checking if you have HTTP::Server::Simple::PSGI 0.14 ... Yes (0.16)
Checking if you have Plack::Middleware::Debug 0.14 ... Yes (0.16)
Checking if you have Plack 1.0023 ... Yes (1.0034)
Checking if you have Twiggy 0.1021 ... No
Checking if you have Plack::Middleware::ReverseProxy 0.15 ... Yes (0.15)
Checking if you have Net::FastCGI 0.14 ... Yes (0.14)
Checking if you have Corona 0.1004 ... Yes (0.1004)
Checking if you have Plack::Middleware::Header 0.04 ... Yes (0.04)
Checking if you have PSGI 1.101 ... Yes (1.102)
Checking if you have Starlet 0.18 ... Yes (0.24)
Checking if you have Plack::Middleware::Session 0.18 ... Yes (0.30)
==> Found dependencies: Twiggy
Searching Twiggy (0.1021) on cpanmetadb ...
--> Working on Twiggy
Fetching http://www.cpan.org/authors/id/M/MI/MIYAGAWA/Twiggy-0.1025.tar.gz
-> OK
Unpacking Twiggy-0.1025.tar.gz
Entering Twiggy-0.1025
Checking configure dependencies from META.json
Checking if you have ExtUtils::MakeMaker 6.58 ... Yes (7.04)
Configuring Twiggy-0.1025
Running Makefile.PL
Checking if your kit is complete...
Looks good
Generating a Unix-style Makefile
Writing Makefile for Twiggy
Writing MYMETA.yml and MYMETA.json
-> OK
Checking dependencies from MYMETA.json ...
Checking if you have Test::More 0 ... Yes (1.001014)
Checking if you have Test::Requires 0 ... Yes (0.08)
Checking if you have Try::Tiny 0 ... Yes (0.22)
Checking if you have Test::TCP 0 ... Yes (2.12)
Checking if you have AnyEvent 0 ... Yes (7.09)
Checking if you have Plack 0.99 ... Yes (1.0034)
Checking if you have ExtUtils::MakeMaker 0 ... Yes (7.04)
Checking if you have HTTP::Status 0 ... Yes (5.817)
Building and testing Twiggy-0.1025
cp lib/Twiggy/Server/SS.pm blib/lib/Twiggy/Server/SS.pm
cp lib/Twiggy.pm blib/lib/Twiggy.pm
cp lib/Twiggy/Server.pm blib/lib/Twiggy/Server.pm
cp lib/Plack/Handler/Twiggy.pm blib/lib/Plack/Handler/Twiggy.pm
cp lib/AnyEvent/Server/PSGI.pm blib/lib/AnyEvent/Server/PSGI.pm
cp script/twiggy blib/script/twiggy
"/usr/bin/perl" -MExtUtils::MY -e 'MY->fixin(shift)' -- blib/script/twiggy
Manifying 1 pod document
Manifying 2 pod documents
PERL_DL_NONLAZY=1 "/usr/bin/perl" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
t/00_compile.t .................. ok
t/anyevent.t .................... ok
t/anyevent_closed_connection.t .. ok

#   Failed test 'streaming response should succeed'
#   at /usr/local/share/perl5/AnyEvent/HTTP.pm line 996.
#          got: '400'
#     expected: '200'
Argument "<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http:..." isn't numeric in numeric eq (==) at t/anyevent_closed_streaming.t line 80.
Argument " Stylesheet for Squid Error pages" isn't numeric in numeric eq (==) at t/anyevent_closed_streaming.t line 80.
Argument " Adapted from design by Free CSS Templates" isn't numeric in numeric eq (==) at t/anyevent_closed_streaming.t line 80.
Argument " http://www.freecsstemplates.org" isn't numeric in numeric eq (==) at t/anyevent_closed_streaming.t line 80.
Argument " Released for free under a Creative Commons Attribution ..." isn't numeric in numeric eq (==) at t/anyevent_closed_streaming.t line 80.
Argument "*/" isn't numeric in numeric eq (==) at t/anyevent_closed_streaming.t line 80.
Argument "" isn't numeric in numeric eq (==) at t/anyevent_closed_streaming.t line 80.
Argument "/* Page basics */" isn't numeric in numeric eq (==) at t/anyevent_closed_streaming.t line 80.
Argument "* {" isn't numeric in numeric eq (==) at t/anyevent_closed_streaming.t line 80.
Argument "^Ifont-family: verdana, sans-serif;" isn't numeric in numeric eq (==) at t/anyevent_closed_streaming.t line 80.
Argument "}" isn't numeric in numeric eq (==) at t/anyevent_closed_streaming.t line 80.
Argument "" isn't numeric in numeric eq (==) at t/anyevent_closed_streaming.t line 80.
Argument "html body {" isn't numeric in numeric eq (==) at t/anyevent_closed_streaming.t line 80.
Argument "^Imargin: 0;" isn't numeric in numeric eq (==) at t/anyevent_closed_streaming.t line 80.
Argument "^Ipadding: 0;" isn't numeric in numeric eq (==) at t/anyevent_closed_streaming.t line 80.
Argument "^Ibackground: #efefef;" isn't numeric in numeric eq (==) at t/anyevent_closed_streaming.t line 80.
Argument "^Ifont-size: 12px;" isn't numeric in numeric eq (==) at t/anyevent_closed_streaming.t line 80.
Argument "^Icolor: #1e1e1e;" isn't numeric in numeric eq (==) at t/anyevent_closed_streaming.t line 80.
Argument "}" isn't numeric in numeric eq (==) at t/anyevent_closed_streaming.t line 80.
Argument "" isn't numeric in numeric eq (==) at t/anyevent_closed_streaming.t line 80.
Argument "/* Page displayed title area */" isn't numeric in numeric eq (==) at t/anyevent_closed_streaming.t line 80.
Argument "#titles {" isn't numeric in numeric eq (==) at t/anyevent_closed_streaming.t line 80.
Argument "^Imargin-left: 15px;" isn't numeric in numeric eq (==) at t/anyevent_closed_streaming.t line 80.
Argument "^Ipadding: 10px;" isn't numeric in numeric eq (==) at t/anyevent_closed_streaming.t line 80.
Argument "^Ipadding-left: 100px;" isn't numeric in numeric eq (==) at t/anyevent_closed_streaming.t line 80.
Argument "^Ibackground: url('http://www.squid-cache.org/Artwork/SN..." isn't numeric in numeric eq (==) at t/anyevent_closed_streaming.t line 80.
Argument "}" isn't numeric in numeric eq (==) at t/anyevent_closed_streaming.t line 80.
Argument "" isn't numeric in numeric eq (==) at t/anyevent_closed_streaming.t line 80.
Argument "/* initial title */" isn't numeric in numeric eq (==) at t/anyevent_closed_streaming.t line 80.
Argument "#titles h1 {" isn't numeric in numeric eq (==) at t/anyevent_closed_streaming.t line 80.
Argument "^Icolor: #000000;" isn't numeric in numeric eq (==) at t/anyevent_closed_streaming.t line 80.
Argument "}" isn't numeric in numeric eq (==) at t/anyevent_closed_streaming.t line 80.
Argument "#titles h2 {" isn't numeric in numeric eq (==) at t/anyevent_closed_streaming.t line 80.
Argument "^Icolor: #000000;" isn't numeric in numeric eq (==) at t/anyevent_closed_streaming.t line 80.
Argument "}" isn't numeric in numeric eq (==) at t/anyevent_closed_streaming.t line 80.
Argument "" isn't numeric in numeric eq (==) at t/anyevent_closed_streaming.t line 80.
Argument "/* special event: FTP success page titles */" isn't numeric in numeric eq (==) at t/anyevent_closed_streaming.t line 80.
Argument "#titles ftpsuccess {" isn't numeric in numeric eq (==) at t/anyevent_closed_streaming.t line 80.
Argument "^Ibackground-color:#00ff00;" isn't numeric in numeric eq (==) at t/anyevent_closed_streaming.t line 80.
Argument "^Iwidth:100%;" isn't numeric in numeric eq (==) at t/anyevent_closed_streaming.t line 80.
Argument "}" isn't numeric in numeric eq (==) at t/anyevent_closed_streaming.t line 80.
Argument "" isn't numeric in numeric eq (==) at t/anyevent_closed_streaming.t line 80.
Argument "/* Page displayed body content area */" isn't numeric in numeric eq (==) at t/anyevent_closed_streaming.t line 80.
Argument "#content {" isn't numeric in numeric eq (==) at t/anyevent_closed_streaming.t line 80.
Argument "^Ipadding: 10px;" isn't numeric in numeric eq (==) at t/anyevent_closed_streaming.t line 80.
Argument "^Ibackground: #ffffff;" isn't numeric in numeric eq (==) at t/anyevent_closed_streaming.t line 80.
Argument "}" isn't numeric in numeric eq (==) at t/anyevent_closed_streaming.t line 80.
Argument "" isn't numeric in numeric eq (==) at t/anyevent_closed_streaming.t line 80.
Argument "/* General text */" isn't numeric in numeric eq (==) at t/anyevent_closed_streaming.t line 80.
Argument "p {" isn't numeric in numeric eq (==) at t/anyevent_closed_streaming.t line 80.
Argument "}" isn't numeric in numeric eq (==) at t/anyevent_closed_streaming.t line 80.
Argument "" isn't numeric in numeric eq (==) at t/anyevent_closed_streaming.t line 80.
Argument "/* error brief description */" isn't numeric in numeric eq (==) at t/anyevent_closed_streaming.t line 80.
Argument "#error p {" isn't numeric in numeric eq (==) at t/anyevent_closed_streaming.t line 80.
Argument "}" isn't numeric in numeric eq (==) at t/anyevent_closed_streaming.t line 80.
Argument "" isn't numeric in numeric eq (==) at t/anyevent_closed_streaming.t line 80.
Argument "/* some data which may have caused the problem */" isn't numeric in numeric eq (==) at t/anyevent_closed_streaming.t line 80.
Argument "#data {" isn't numeric in numeric eq (==) at t/anyevent_closed_streaming.t line 80.
Argument "}" isn't numeric in numeric eq (==) at t/anyevent_closed_streaming.t line 80.
Argument "" isn't numeric in numeric eq (==) at t/anyevent_closed_streaming.t line 80.
Argument "/* the error message received from the system or other s..." isn't numeric in numeric eq (==) at t/anyevent_closed_streaming.t line 80.
Argument "#sysmsg {" isn't numeric in numeric eq (==) at t/anyevent_closed_streaming.t line 80.
Argument "}" isn't numeric in numeric eq (==) at t/anyevent_closed_streaming.t line 80.
Argument "" isn't numeric in numeric eq (==) at t/anyevent_closed_streaming.t line 80.
Argument "pre {" isn't numeric in numeric eq (==) at t/anyevent_closed_streaming.t line 80.
Argument "    font-family:sans-serif;" isn't numeric in numeric eq (==) at t/anyevent_closed_streaming.t line 80.
Argument "}" isn't numeric in numeric eq (==) at t/anyevent_closed_streaming.t line 80.
Argument "" isn't numeric in numeric eq (==) at t/anyevent_closed_streaming.t line 80.
Argument "/* special event: FTP / Gopher directory listing */" isn't numeric in numeric eq (==) at t/anyevent_closed_streaming.t line 80.
Argument "#dirmsg {" isn't numeric in numeric eq (==) at t/anyevent_closed_streaming.t line 80.
Argument "    font-family: courier;" isn't numeric in numeric eq (==) at t/anyevent_closed_streaming.t line 80.
Argument "    color: black;" isn't numeric in numeric eq (==) at t/anyevent_closed_streaming.t line 80.
Argument "    font-size: 10pt;" isn't numeric in numeric eq (==) at t/anyevent_closed_streaming.t line 80.
Argument "}" isn't numeric in numeric eq (==) at t/anyevent_closed_streaming.t line 80.
Argument "#dirlisting {" isn't numeric in numeric eq (==) at t/anyevent_closed_streaming.t line 80.
Argument "    margin-left: 2%;" isn't numeric in numeric eq (==) at t/anyevent_closed_streaming.t line 80.
Argument "    margin-right: 2%;" isn't numeric in numeric eq (==) at t/anyevent_closed_streaming.t line 80.
Argument "}" isn't numeric in numeric eq (==) at t/anyevent_closed_streaming.t line 80.
Argument "#dirlisting tr.entry td.icon,td.filename,td.size,td.date..." isn't numeric in numeric eq (==) at t/anyevent_closed_streaming.t line 80.
Argument "    border-bottom: groove;" isn't numeric in numeric eq (==) at t/anyevent_closed_streaming.t line 80.
Argument "}" isn't numeric in numeric eq (==) at t/anyevent_closed_streaming.t line 80.
Argument "#dirlisting td.size {" isn't numeric in numeric eq (==) at t/anyevent_closed_streaming.t line 80.
Argument "    width: 50px;" isn't numeric in numeric eq (==) at t/anyevent_closed_streaming.t line 80.
Argument "    text-align: right;" isn't numeric in numeric eq (==) at t/anyevent_closed_streaming.t line 80.
Argument "    padding-right: 5px;" isn't numeric in numeric eq (==) at t/anyevent_closed_streaming.t line 80.
Argument "}" isn't numeric in numeric eq (==) at t/anyevent_closed_streaming.t line 80.
Argument "" isn't numeric in numeric eq (==) at t/anyevent_closed_streaming.t line 80.
Argument "/* horizontal lines */" isn't numeric in numeric eq (==) at t/anyevent_closed_streaming.t line 80.
Argument "hr {" isn't numeric in numeric eq (==) at t/anyevent_closed_streaming.t line 80.
Argument "^Imargin: 0;" isn't numeric in numeric eq (==) at t/anyevent_closed_streaming.t line 80.
Argument "}" isn't numeric in numeric eq (==) at t/anyevent_closed_streaming.t line 80.
Argument "" isn't numeric in numeric eq (==) at t/anyevent_closed_streaming.t line 80.
Argument "/* page displayed footer area */" isn't numeric in numeric eq (==) at t/anyevent_closed_streaming.t line 80.
Argument "#footer {" isn't numeric in numeric eq (==) at t/anyevent_closed_streaming.t line 80.
Argument "^Ifont-size: 9px;" isn't numeric in numeric eq (==) at t/anyevent_closed_streaming.t line 80.
Argument "^Ipadding-left: 10px;" isn't numeric in numeric eq (==) at t/anyevent_closed_streaming.t line 80.
Argument "}" isn't numeric in numeric eq (==) at t/anyevent_closed_streaming.t line 80.

#   Failed test 'Unexpected error: Connection timed out'
#   at /usr/local/lib64/perl5/AnyEvent/Handle.pm line 653.
# Looks like you failed 2 tests of 3.
t/anyevent_closed_streaming.t ...
Dubious, test returned 2 (wstat 512, 0x200)
Failed 2/3 subtests
t/anyevent_extensions.t ......... ok
t/anyevent_manyconnections.t .... skipped: Slow test skipped unless $ENV{TEST_SLOW} is set
start_server (pid:13848) starting now...
starting new worker 13849
received TERM, sending TERM to all workers:13849
worker 13849 died, status:15
exiting
t/anyevent_server_starter.t ..... ok
t/anyevent_slow_post.t .......... ok
t/deflater.t .................... ok
t/disconnect.t .................. ok
t/release-pod-syntax.t .......... skipped: these tests are for release candidate testing
Test Summary Report
-------------------
t/anyevent_closed_streaming.t (Wstat: 512 Tests: 3 Failed: 2)
  Failed tests:  1-2
  Non-zero exit status: 2
Files=11, Tests=130,  8 wallclock secs ( 0.09 usr  0.03 sys +  3.02 cusr  0.51 csys =  3.65 CPU)
Result: FAIL
Failed 1/11 test programs. 2/130 subtests failed.
make: *** [test_dynamic] Error 255
-> FAIL Installing Twiggy failed. See /root/.cpanm/work/1433346584.13768/build.log for details. Retry with --force to force install it.
-> FAIL Installing the dependencies failed: Module 'Twiggy' is not installed
-> FAIL Bailing out the installation for Task-Plack-0.28.

**Comment by miyagawa** [comment]
The test looks like it's hitting a proxy, and has very little to do with the test itself.
